/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LanesRouteImport } from './routes/lanes'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsWorkflowIdIndexRouteImport } from './routes/workflows.$workflowId.index'
import { Route as WorkflowsWorkflowIdVersionsRouteImport } from './routes/workflows.$workflowId.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesRoute = LanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdIndexRoute =
  WorkflowsWorkflowIdIndexRouteImport.update({
    id: '/workflows/$workflowId/',
    path: '/workflows/$workflowId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowIdVersionsRoute =
  WorkflowsWorkflowIdVersionsRouteImport.update({
    id: '/workflows/$workflowId/versions',
    path: '/workflows/$workflowId/versions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/lanes': typeof LanesRoute
  '/mcp': typeof McpRoute
  '/observability': typeof ObservabilityRoute
  '/policies': typeof PoliciesRoute
  '/providers': typeof ProvidersRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$workflowId/versions': typeof WorkflowsWorkflowIdVersionsRoute
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/lanes': typeof LanesRoute
  '/mcp': typeof McpRoute
  '/observability': typeof ObservabilityRoute
  '/policies': typeof PoliciesRoute
  '/providers': typeof ProvidersRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs': typeof RunsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$workflowId/versions': typeof WorkflowsWorkflowIdVersionsRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/lanes': typeof LanesRoute
  '/mcp': typeof McpRoute
  '/observability': typeof ObservabilityRoute
  '/policies': typeof PoliciesRoute
  '/providers': typeof ProvidersRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$workflowId/versions': typeof WorkflowsWorkflowIdVersionsRoute
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/lanes'
    | '/mcp'
    | '/observability'
    | '/policies'
    | '/providers'
    | '/secrets'
    | '/settings'
    | '/skills'
    | '/runs/$runId'
    | '/runs/'
    | '/workflows/'
    | '/workflows/$workflowId/versions'
    | '/workflows/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/lanes'
    | '/mcp'
    | '/observability'
    | '/policies'
    | '/providers'
    | '/secrets'
    | '/settings'
    | '/skills'
    | '/runs/$runId'
    | '/runs'
    | '/workflows'
    | '/workflows/$workflowId/versions'
    | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/lanes'
    | '/mcp'
    | '/observability'
    | '/policies'
    | '/providers'
    | '/secrets'
    | '/settings'
    | '/skills'
    | '/runs/$runId'
    | '/runs/'
    | '/workflows/'
    | '/workflows/$workflowId/versions'
    | '/workflows/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LanesRoute: typeof LanesRoute
  McpRoute: typeof McpRoute
  ObservabilityRoute: typeof ObservabilityRoute
  PoliciesRoute: typeof PoliciesRoute
  ProvidersRoute: typeof ProvidersRoute
  SecretsRoute: typeof SecretsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsWorkflowIdVersionsRoute: typeof WorkflowsWorkflowIdVersionsRoute
  WorkflowsWorkflowIdIndexRoute: typeof WorkflowsWorkflowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes': {
      id: '/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof LanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/': {
      id: '/workflows/$workflowId/'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof WorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/versions': {
      id: '/workflows/$workflowId/versions'
      path: '/workflows/$workflowId/versions'
      fullPath: '/workflows/$workflowId/versions'
      preLoaderRoute: typeof WorkflowsWorkflowIdVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LanesRoute: LanesRoute,
  McpRoute: McpRoute,
  ObservabilityRoute: ObservabilityRoute,
  PoliciesRoute: PoliciesRoute,
  ProvidersRoute: ProvidersRoute,
  SecretsRoute: SecretsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsWorkflowIdVersionsRoute: WorkflowsWorkflowIdVersionsRoute,
  WorkflowsWorkflowIdIndexRoute: WorkflowsWorkflowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
