#!/usr/bin/env bash
# verify-docs.sh — keep relay-x documentation truthful.
#
# Computes canonical facts from the code and fails when the docs disagree.
# This is the enforcement behind the "Documentation sync" rule in AGENTS.md:
# a stale doc is a failing check, not a review comment.
#
# Usage:
#   scripts/verify-docs.sh           # verify (exit 1 on drift)
#   scripts/verify-docs.sh --write   # regenerate the canonical-facts block
#   scripts/verify-docs.sh --quiet   # print failures only
#
# Facts are counted statically, so the check needs no database and no test
# run:
#   Rust — `#[test]` / `#[tokio::test]` attributes under apps/ + crates/
#   Web  — `test(` / `it(` declarations in apps/web/src/**/*.test.ts(x)
#   CP   — same, in apps/control-plane/tests/*.test.ts
# Static counts equal executed tests here: the repo uses no `.skip`, `.todo`,
# or `.each` (verified; `test.each` would undercount, `.skip` would overcount).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MODE="check"
QUIET=0
for arg in "$@"; do
  case "$arg" in
    --write) MODE="write" ;;
    --quiet) QUIET=1 ;;
    -h|--help) sed -n '2,17p' "$0"; exit 0 ;;
    *) echo "Usage: $0 [--write|--quiet]" >&2; exit 2 ;;
  esac
done

FAILED=0
fail() { printf ' %s\n' "$1" >&2; FAILED=1; }
ok() { [ "$QUIET" -eq 1 ] || printf '✓ %s\n' "$1"; }
say() { [ "$QUIET" -eq 1 ] || printf '%s\n' "$1"; }

FACTS_DOC="docs/state.md"
FACTS_BEGIN='<!-- BEGIN CANONICAL FACTS'
FACTS_END='<!-- END CANONICAL FACTS -->'

# ── Canonical facts (computed from code) ────────────────────

count_rust() { # <dir>
  { grep -rhoE '#\[(tokio::)?test\]' "$1" --include='*.rs' 2>/dev/null || true; } | wc -l | tr -d ' '
}

count_js() { # <dir>
  { grep -rhE '^[[:space:]]*(test|it)(\.(skip|only|todo|each|concurrent|failing))?\(' \
    "$1" --include='*.test.ts' --include='*.test.tsx' 2>/dev/null || true; } | wc -l | tr -d ' '
}

RUST_GATEWAY="$(count_rust apps/gateway)"
RUST_PROTOCOL_CORE="$(count_rust crates/protocol-core)"
RUST_WORKFLOW_SCHEMA="$(count_rust crates/workflow-schema)"
RUST_WORKFLOW_RUNTIME="$(count_rust crates/workflow-runtime)"
RUST_MOCK_UPSTREAM="$(count_rust crates/mock-upstream)"
RUST_TEST_HARNESS="$(count_rust crates/test-harness)"
RUST_TOTAL=$((RUST_GATEWAY + RUST_PROTOCOL_CORE + RUST_WORKFLOW_SCHEMA \
  + RUST_WORKFLOW_RUNTIME + RUST_MOCK_UPSTREAM + RUST_TEST_HARNESS))
WEB_TESTS="$(count_js apps/web/src)"
CP_TESTS="$(count_js apps/control-plane/tests)"
PAGE_ROUTES="$(find apps/web/src/routes -name '*.tsx' ! -name '__root.tsx' 2>/dev/null | wc -l | tr -d ' ')"

render_facts() {
  cat <<EOF
$FACTS_BEGIN (generated by scripts/verify-docs.sh --write — do not hand-edit) -->
| Fact | Value |
| ---- | ----- |
| rust_tests_total | $RUST_TOTAL |
| rust_tests_gateway | $RUST_GATEWAY |
| rust_tests_protocol_core | $RUST_PROTOCOL_CORE |
| rust_tests_workflow_schema | $RUST_WORKFLOW_SCHEMA |
| rust_tests_workflow_runtime | $RUST_WORKFLOW_RUNTIME |
| rust_tests_mock_upstream | $RUST_MOCK_UPSTREAM |
| web_tests | $WEB_TESTS |
| control_plane_tests | $CP_TESTS |
| page_routes | $PAGE_ROUTES |
$FACTS_END
EOF
}

extract_fact() { # <key>; reads a facts table on stdin
  awk -F'|' -v k="$1" '
    {
      key = $2; gsub(/^[ \t]+|[ \t]+$/, "", key)
      if (key == k) {
        v = $3; gsub(/^[ \t]+|[ \t]+$/, "", v)
        print v
      }
    }
  '
}
if [ "$MODE" = "write" ]; then
  if ! grep -q "$FACTS_BEGIN" "$FACTS_DOC"; then
    echo "✗ $FACTS_DOC has no canonical-facts block; add the BEGIN/END markers first." >&2
    exit 1
  fi
  block="$(render_facts)"
  tmp="$(mktemp)"
  awk -v begin="$FACTS_BEGIN" -v end="$FACTS_END" -v block="$block" '
    index($0, begin) { print block; skip = 1; next }
    skip && index($0, end) { skip = 0; next }
    !skip { print }
  ' "$FACTS_DOC" > "$tmp"
  mv "$tmp" "$FACTS_DOC"
  say "✓ rewrote canonical-facts block in $FACTS_DOC"
  say "  rust=$RUST_TOTAL web=$WEB_TESTS control-plane=$CP_TESTS routes=$PAGE_ROUTES"
  exit 0
fi

# ── Check 1: canonical-facts block matches the code ──────────

if ! grep -q "$FACTS_BEGIN" "$FACTS_DOC"; then
  fail "$FACTS_DOC is missing the canonical-facts block ($FACTS_BEGIN)"
else
  block="$(awk -v begin="$FACTS_BEGIN" -v end="$FACTS_END" '
    index($0, begin) { skip = 1; next }
    index($0, end) { skip = 0 }
    skip { print }
  ' "$FACTS_DOC")"
  for fact in rust_tests_total rust_tests_gateway rust_tests_protocol_core \
    rust_tests_workflow_schema rust_tests_workflow_runtime \
    rust_tests_mock_upstream web_tests control_plane_tests page_routes; do
    want="$(render_facts | extract_fact "$fact")"
    got="$(printf '%s\n' "$block" | extract_fact "$fact")"
    if [ -z "$want" ]; then
      fail "internal error: cannot compute canonical fact '$fact'"
    elif [ "$got" != "$want" ]; then
      fail "canonical fact '$fact' is ${got:-missing}, code says $want (run: scripts/verify-docs.sh --write)"
    else
      ok "canonical fact $fact = $want"
    fi
  done
fi

# ── Check 2: numbers quoted in prose docs match the code ─────

assert_quoted() { # <file> <regex> <expected> <label>
  local file="$1" regex="$2" expected="$3" label="$4" found
  [ -f "$file" ] || { fail "$label: $file does not exist"; return; }
  found="$(grep -oE "$regex" "$file" 2>/dev/null | grep -oE '[0-9]+' | head -1 || true)"
  if [ "$found" != "$expected" ]; then
    fail "$label: $file quotes '${found:-no number}', code says $expected"
  else
    ok "$label"
  fi
}

assert_quoted "README.md" 'Rust tests \| — \| [0-9]+ passing' "$RUST_TOTAL" "README rust test count"
assert_quoted "README.md" 'Frontend tests \| — \| [0-9]+ passing' "$WEB_TESTS" "README frontend test count"
assert_quoted "README.md" 'Control-plane integration tests \| — \| [0-9]+ passing' "$CP_TESTS" "README control-plane test count"
assert_quoted "docs/testing.md" '[0-9]+ tests in `crates/protocol-core/`' "$RUST_PROTOCOL_CORE" "testing.md protocol-core count"
assert_quoted "docs/testing.md" 'has [0-9]+ frontend tests' "$WEB_TESTS" "testing.md web count"
assert_quoted "$FACTS_DOC" 'Rust [0-9]+ passing' "$RUST_TOTAL" "state.md rust total"

# ─ Check 3: relative markdown links resolve ─────────────────

missing_links=0
while IFS= read -r entry; do
  [ -n "$entry" ] || continue
  file="${entry%%:*}"
  target="${entry#*:}"
  case "$target" in
    http*|\#*|mailto:*) continue ;;
  esac
  path="${target%%#*}"
  case "$path" in *.md) ;; *) continue ;; esac
  if [ ! -e "$(dirname "$file")/$path" ]; then
    fail "broken link in $file → $target"
    missing_links=$((missing_links + 1))
  fi
done < <({ find docs -name '*.md' -print0; printf '%s\0' README.md AGENTS.md CLAUDE.md; } 2>/dev/null \
  | xargs -0 grep -HoE '\]\([^)]+\)' 2>/dev/null \
  | sed -E 's/:]\((.*)\)$/:\1/' || true)
[ "$missing_links" -eq 0 ] && ok "all relative doc links resolve"
# ─ Check 4: docs/ top level holds only living docs ──────────
# Dated snapshots (phase reports, audits, superseded state) belong in
# docs/archive/ so an agent can never mistake a snapshot for current truth.

snapshots=0
for f in docs/*.md; do
  base="${f##*/}"
  case "$base" in
    PHASE*|CURRENT_STATE.md|*AUDIT*|*-report.md|phase-*-report.md|*_REPORT.md)
      fail "snapshot file at docs/ top level: $f (move it to docs/archive/)"
      snapshots=$((snapshots + 1))
      ;;
  esac
done
[ "$snapshots" -eq 0 ] && ok "docs/ top level holds only living docs"

# ── Check 5: living docs carry the convention header ─────────
# Top level docs must be `living`; snapshots belong in docs/archive/.
# ADRs are exempt: they carry a `## Status` section instead.

header_re='^> \*\*Status:\*\* living · \*\*Verified:\*\* [0-9]{4}-[0-9]{2}-[0-9]{2} · \*\*Purpose:\*\* .+'
bad_headers=0
for f in docs/*.md; do
  base="${f##*/}"
  case "$base" in
    adr-*.md)
      grep -qE '^## Status' "$f" || { fail "$f is an ADR without a '## Status' section"; bad_headers=$((bad_headers + 1)); }
      continue
      ;;
  esac
  grep -qE "$header_re" "$f" || {
    fail "$f is missing the doc header (Status/Verified/Purpose)"
    bad_headers=$((bad_headers + 1))
  }
done
[ "$bad_headers" -eq 0 ] && ok "living docs carry the convention header"

if [ "$FAILED" -ne 0 ]; then
  echo >&2
  echo "Documentation drift detected." >&2
  echo "Fix the docs (or the code) and re-run: scripts/verify-docs.sh" >&2
  echo "Regenerate canonical facts with: scripts/verify-docs.sh --write" >&2
  exit 1
fi

say ""
say "✓ documentation matches the code (rust=$RUST_TOTAL web=$WEB_TESTS control-plane=$CP_TESTS routes=$PAGE_ROUTES)"