export type Health = "healthy" | "degraded" | "failed" | "idle";

export const workspace = {
  name: "acme-platform",
  environments: ["Production", "Staging", "Development"],
  user: { name: "Ilya Novak", email: "ilya@acme.dev", initials: "IN" },
};

export const workflows = [
  {
    id: "production-gateway",
    name: "Production Gateway",
    version: 24,
    state: "Deployed" as const,
    env: "Production",
    nodes: 11,
    p95: "184 ms",
    rps: "412",
    updated: "2 min ago",
    owner: "platform-core",
  },
  {
    id: "batch-summarizer",
    name: "Batch Summarizer",
    version: 9,
    state: "Draft" as const,
    env: "Staging",
    nodes: 7,
    p95: "1.9 s",
    rps: "6",
    updated: "3 hours ago",
    owner: "data-eng",
  },
  {
    id: "support-agent",
    name: "Customer Support Agent",
    version: 17,
    state: "Deployed" as const,
    env: "Production",
    nodes: 14,
    p95: "310 ms",
    rps: "88",
    updated: "yesterday",
    owner: "support-eng",
  },
  {
    id: "eval-harness",
    name: "Eval Harness",
    version: 4,
    state: "Invalid" as const,
    env: "Development",
    nodes: 9,
    p95: "—",
    rps: "0",
    updated: "4 days ago",
    owner: "research",
  },
];

export const versions = [
  {
    v: 24,
    status: "Production",
    when: "2 min ago",
    author: "ilya",
    note: "Add EU lane fallback + retry budget",
    plan: "plan_8f31a2",
  },
  {
    v: 23,
    status: "Production",
    when: "yesterday",
    author: "ilya",
    note: "Latency-aware router strategy",
    plan: "plan_71c0d4",
  },
  {
    v: 22,
    status: "Archived",
    when: "3 days ago",
    author: "marta",
    note: "MCP discovery policy filter",
    plan: "plan_5ab913",
  },
  {
    v: 21,
    status: "Archived",
    when: "6 days ago",
    author: "marta",
    note: "Initial streaming output",
    plan: "plan_22ee80",
  },
];

export const compileStages = [
  { name: "React Flow graph", detail: "11 nodes · 13 edges", ms: "—", state: "ok" },
  { name: "Schema validation", detail: "JSON schema draft 2020-12", ms: "3.1 ms", state: "ok" },
  { name: "Semantic validation", detail: "cycles, orphans, handle types", ms: "5.8 ms", state: "ok" },
  { name: "Capability resolution", detail: "4 providers · 18 capabilities", ms: "11.4 ms", state: "ok" },
  { name: "Policy compilation", detail: "9 rules → deterministic matcher", ms: "7.2 ms", state: "ok" },
  { name: "Lane validation", detail: "3 lanes · endpoint permits", ms: "4.6 ms", state: "warn" },
  { name: "Optimization", detail: "constant folding · handle inlining", ms: "2.9 ms", state: "ok" },
  { name: "Execution plan v24", detail: "plan_8f31a2 · 14.2 KB", ms: "—", state: "ok" },
];

export const runs = [
  {
    id: "8F31A2",
    workflow: "Production Gateway",
    version: 24,
    route: "claude-*",
    lane: "anthropic-us-vpn",
    provider: "Anthropic",
    ttfb: "420 ms",
    total: "1.82 s",
    gateway: "3.4 ms",
    status: "Completed",
    when: "12s ago",
  },
  {
    id: "7C20B9",
    workflow: "Production Gateway",
    version: 24,
    route: "gpt-*",
    lane: "openai-direct",
    provider: "OpenAI",
    ttfb: "512 ms",
    total: "2.41 s",
    gateway: "2.9 ms",
    status: "Completed",
    when: "18s ago",
  },
  {
    id: "6B18F4",
    workflow: "Customer Support Agent",
    version: 17,
    route: "claude-*",
    lane: "anthropic-eu-vpn",
    provider: "Anthropic",
    ttfb: "688 ms",
    total: "3.10 s",
    gateway: "4.1 ms",
    status: "Degraded",
    when: "34s ago",
  },
  {
    id: "5A02C1",
    workflow: "Production Gateway",
    version: 24,
    route: "claude-*",
    lane: "anthropic-us-vpn",
    provider: "Anthropic",
    ttfb: "—",
    total: "902 ms",
    gateway: "3.2 ms",
    status: "Failed",
    when: "1m ago",
  },
  {
    id: "4E91D7",
    workflow: "Batch Summarizer",
    version: 9,
    route: "gpt-*",
    lane: "openai-direct",
    provider: "OpenAI",
    ttfb: "340 ms",
    total: "1.12 s",
    gateway: "2.7 ms",
    status: "Completed",
    when: "2m ago",
  },
  {
    id: "3D77A8",
    workflow: "Production Gateway",
    version: 23,
    route: "claude-*",
    lane: "anthropic-us-vpn",
    provider: "Anthropic",
    ttfb: "455 ms",
    total: "1.98 s",
    gateway: "3.6 ms",
    status: "Completed",
    when: "2m ago",
  },
  {
    id: "2C55E3",
    workflow: "Customer Support Agent",
    version: 17,
    route: "mistral-*",
    lane: "proxy-apac",
    provider: "Mistral",
    ttfb: "790 ms",
    total: "2.66 s",
    gateway: "5.2 ms",
    status: "Completed",
    when: "3m ago",
  },
  {
    id: "1B34F0",
    workflow: "Production Gateway",
    version: 24,
    route: "claude-*",
    lane: "anthropic-us-vpn",
    provider: "Anthropic",
    ttfb: "—",
    total: "128 ms",
    gateway: "2.4 ms",
    status: "Cancelled",
    when: "4m ago",
  },
];

export const waterfall = [
  { phase: "Authentication", ms: 0.2, kind: "gateway" },
  { phase: "Config snapshot", ms: 0.1, kind: "gateway" },
  { phase: "Route selection", ms: 0.1, kind: "gateway" },
  { phase: "Lane selection", ms: 0.1, kind: "gateway" },
  { phase: "Connection acquire", ms: 0.4, kind: "gateway" },
  { phase: "Translation", ms: 1.2, kind: "gateway" },
  { phase: "Upstream TTFB", ms: 420, kind: "upstream" },
  { phase: "Streaming", ms: 1390, kind: "upstream" },
];

export const providers = [
  {
    id: "anthropic",
    name: "Anthropic",
    protocol: "Messages API v1",
    status: "healthy" as Health,
    endpoints: ["api.anthropic.com", "vertex-anthropic.googleapis.com"],
    models: ["Claude Sonnet 4.5", "Claude Opus 4.1", "Claude Haiku 4"],
    latency: "82 ms",
    error: "0.04%",
    lanes: 2,
    tokens: "48.2M / day",
  },
  {
    id: "openai",
    name: "OpenAI",
    protocol: "Responses API",
    status: "healthy" as Health,
    endpoints: ["api.openai.com"],
    models: ["gpt-5.1", "gpt-5.1-mini", "o4-mini"],
    latency: "104 ms",
    error: "0.11%",
    lanes: 1,
    tokens: "31.7M / day",
  },
  {
    id: "mistral",
    name: "Mistral",
    protocol: "Chat Completions",
    status: "degraded" as Health,
    endpoints: ["api.mistral.ai"],
    models: ["mistral-large-3", "codestral-2"],
    latency: "241 ms",
    error: "1.86%",
    lanes: 1,
    tokens: "4.1M / day",
  },
  {
    id: "bedrock",
    name: "AWS Bedrock",
    protocol: "Converse API",
    status: "idle" as Health,
    endpoints: ["bedrock-runtime.us-east-1.amazonaws.com"],
    models: ["anthropic.claude-sonnet-4-5", "meta.llama-4-70b"],
    latency: "—",
    error: "—",
    lanes: 0,
    tokens: "0",
  },
];

export const capabilityMatrix = {
  columns: ["Anthropic", "OpenAI", "Mistral", "Bedrock"],
  rows: [
    { name: "Streaming", values: [true, true, true, true] },
    { name: "Tools", values: [true, true, true, true] },
    { name: "Reasoning", values: [true, true, false, true] },
    { name: "Structured output", values: [true, true, true, false] },
    { name: "Deferred tools", values: [true, false, false, false] },
    { name: "Images", values: [true, true, false, true] },
    { name: "Prompt caching", values: [true, true, false, true] },
    { name: "Batch", values: [true, true, false, false] },
  ],
};

export const lanes = [
  {
    id: "anthropic-us-vpn",
    provider: "Anthropic",
    endpoint: "production",
    network: "WireGuard US-01",
    region: "US-East",
    policy: "production-standard",
    pool: 48,
    health: "healthy" as Health,
    latency: "82 ms",
    reuse: "94.2%",
    errors: "0.04%",
  },
  {
    id: "anthropic-eu-vpn",
    provider: "Anthropic",
    endpoint: "production",
    network: "WireGuard EU-03",
    region: "EU-Frankfurt",
    policy: "eu-residency",
    pool: 24,
    health: "healthy" as Health,
    latency: "119 ms",
    reuse: "91.0%",
    errors: "0.07%",
  },
  {
    id: "openai-direct",
    provider: "OpenAI",
    endpoint: "production",
    network: "Direct egress",
    region: "US-West",
    policy: "production-standard",
    pool: 36,
    health: "healthy" as Health,
    latency: "104 ms",
    reuse: "88.6%",
    errors: "0.11%",
  },
  {
    id: "proxy-apac",
    provider: "Mistral",
    endpoint: "production",
    network: "HTTP proxy APAC-02",
    region: "AP-Singapore",
    policy: "restricted",
    pool: 12,
    health: "degraded" as Health,
    latency: "241 ms",
    reuse: "62.3%",
    errors: "1.86%",
  },
];

export const mcpServers = [
  { name: "github", transport: "streamable-http", tools: 412, status: "healthy" as Health, scope: "org", indexed: "2 min ago" },
  { name: "linear", transport: "streamable-http", tools: 96, status: "healthy" as Health, scope: "org", indexed: "9 min ago" },
  { name: "postgres-readonly", transport: "stdio", tools: 18, status: "healthy" as Health, scope: "project", indexed: "1 h ago" },
  { name: "sentry", transport: "sse", tools: 64, status: "degraded" as Health, scope: "org", indexed: "22 min ago" },
  { name: "internal-search", transport: "streamable-http", tools: 1252, status: "healthy" as Health, scope: "tenant", indexed: "4 min ago" },
];

export const mcpTools = [
  { name: "github.read_pr", server: "github", score: 0.94, permitted: true, activated: true, calls: "12.4k" },
  { name: "github.list_reviews", server: "github", score: 0.91, permitted: true, activated: true, calls: "9.1k" },
  { name: "github.read_diff", server: "github", score: 0.88, permitted: true, activated: false, calls: "6.8k" },
  { name: "github.write_issue", server: "github", score: 0.72, permitted: false, activated: false, calls: "0" },
  { name: "linear.search_issues", server: "linear", score: 0.64, permitted: true, activated: false, calls: "2.2k" },
  { name: "sentry.list_events", server: "sentry", score: 0.51, permitted: false, activated: false, calls: "0" },
];

export const skills = [
  {
    name: "code-review",
    version: "1.4.0",
    metadata: true,
    instructions: true,
    references: 2,
    scripts: 1,
    status: "Ready",
    bytes: "18 KB / 412 KB deferred",
  },
  {
    name: "incident-triage",
    version: "0.9.2",
    metadata: true,
    instructions: true,
    references: 5,
    scripts: 3,
    status: "Ready",
    bytes: "22 KB / 1.1 MB deferred",
  },
  {
    name: "sql-optimizer",
    version: "2.0.1",
    metadata: true,
    instructions: false,
    references: 3,
    scripts: 0,
    status: "Metadata only",
    bytes: "4 KB / 260 KB deferred",
  },
  {
    name: "release-notes",
    version: "1.0.0",
    metadata: true,
    instructions: true,
    references: 0,
    scripts: 0,
    status: "Ready",
    bytes: "9 KB",
  },
];

export const policies = [
  {
    id: "pol_prod_support",
    name: "production-support-tools",
    effect: "ALLOW" as const,
    scope: "workflow",
    conditions: [
      "Environment = production",
      "Workflow = customer-support",
      "Tool = github.read_pr",
    ],
    hits: "48.2k / 24h",
    updated: "2 days ago",
  },
  {
    id: "pol_deny_writes",
    name: "deny-write-tools",
    effect: "DENY" as const,
    scope: "tenant",
    conditions: ["Tool matches *.write_*", "Environment = production"],
    hits: "312 / 24h",
    updated: "6 days ago",
  },
  {
    id: "pol_eu_residency",
    name: "eu-residency",
    effect: "ALLOW" as const,
    scope: "endpoint",
    conditions: ["Tenant.region = EU", "Lane.network = WireGuard EU-03"],
    hits: "9.8k / 24h",
    updated: "1 week ago",
  },
  {
    id: "pol_deny_untrusted_mcp",
    name: "deny-unverified-mcp",
    effect: "DENY" as const,
    scope: "mcp server",
    conditions: ["MCP.server.verified = false"],
    hits: "27 / 24h",
    updated: "3 weeks ago",
  },
];

export const latencySeries = Array.from({ length: 40 }, (_, i) => {
  const t = i / 39;
  return {
    t: `${String(23 - Math.floor(t * 23)).padStart(2, "0")}h`,
    p50: 118 + Math.round(Math.sin(i / 3) * 12 + (i % 5) * 2),
    p95: 184 + Math.round(Math.cos(i / 4) * 26 + (i % 7) * 3),
    p99: 268 + Math.round(Math.sin(i / 2.2) * 44 + (i % 6) * 5),
    gateway: 3.1 + Number((Math.sin(i / 5) * 0.6).toFixed(2)),
    upstream: 172 + Math.round(Math.cos(i / 3.4) * 28),
    rps: 380 + Math.round(Math.sin(i / 2.6) * 60 + (i % 4) * 9),
    streams: 120 + Math.round(Math.cos(i / 2.1) * 34),
    errors: Number((0.3 + Math.abs(Math.sin(i / 4.3)) * 0.5).toFixed(2)),
  };
});

export const kpis = [
  { label: "Gateway overhead", value: "3.4", unit: "ms", delta: "-0.2 ms", tone: "ok" as const, hint: "p95 in-process" },
  { label: "Upstream TTFB", value: "420", unit: "ms", delta: "+18 ms", tone: "warn" as const, hint: "p95 provider" },
  { label: "Total latency", value: "1.82", unit: "s", delta: "-40 ms", tone: "ok" as const, hint: "p95 end to end" },
  { label: "Requests / sec", value: "412", unit: "rps", delta: "+6.1%", tone: "ok" as const, hint: "1 min rate" },
  { label: "Active streams", value: "138", unit: "", delta: "+12", tone: "neutral" as const, hint: "open SSE" },
  { label: "Error rate", value: "0.41", unit: "%", delta: "+0.08%", tone: "warn" as const, hint: "5xx + rejections" },
  { label: "Connection reuse", value: "94.2", unit: "%", delta: "+1.4%", tone: "ok" as const, hint: "pooled sockets" },
  { label: "MCP cache hit", value: "97.8", unit: "%", delta: "+0.3%", tone: "ok" as const, hint: "discovery index" },
];

export const validationIssues = [
  {
    level: "error" as const,
    code: "unauthorized_tool",
    node: "MCP Discovery",
    title: "Unauthorized tool",
    detail: "Workflow policy deny-write-tools denies github.write_issue.",
  },
  {
    level: "warn" as const,
    code: "capability_mismatch",
    node: "Provider · OpenAI",
    title: "Capability mismatch",
    detail: "Provider does not support deferred tool references. Requests will drop the deferred set.",
  },
  {
    level: "error" as const,
    code: "invalid_lane",
    node: "Lane · proxy-apac",
    title: "Invalid lane",
    detail: "Lane is not permitted for endpoint api.anthropic.com under policy eu-residency.",
  },
];

export const errorCategories = [
  { code: "translation_error", count: 12 },
  { code: "unsupported_feature", count: 41 },
  { code: "provider_rejection", count: 8 },
  { code: "rate_limit", count: 96 },
  { code: "authentication", count: 3 },
  { code: "network", count: 22 },
  { code: "cancellation", count: 64 },
];
